# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HelloWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWeather

  target 'HelloWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SideMenu'
  pod 'RealmSwift'

end
